### ISSUE TITLE
Signup Functionality: Dropdown Options Hard to Read in Dark Mode

### ISSUE THREAD

**Issue by VivekAlhat** [thefullstackgroup/thefullstack#17]
**Overview**:

In the dark mode of the web app, the dropdown menu's background color remains white, making it difficult to see the options.

**Steps to Reproduce**:
- Enable dark mode in the web app.
- Navigate to the signup page.
- Click on the dropdown menu, e.g., for selecting a country or what do you do section.

**Expected Behavior**:

In dark mode, the dropdown menu should have a color scheme that ensures good visibility of the options, making it user-friendly and aesthetically pleasing.

**Actual Behavior**:

The dropdown menu retains a white background color, causing the options to blend in with the background, resulting in poor visibility and usability.

**Screenshots/GIFs**:

![Signup page](https://github.com/thefullstackgroup/thefullstack/assets/47483669/f4400140-7e78-4276-9330-7da8739ca32d)

**Comment by A-AllaaEddine** [comment]
Got it, will work on that when I can.

**Comment by VivekAlhat** [comment]
Thanks, I've fixed the issue and raised a [PR](https://github.com/thefullstackgroup/webapp/pull/9) as well.

**Comment by danoely1979** [comment]
Nice spot. Good work
